"""
Django settings for sss project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!l+bu2@pc-p80dp(qu9+7!b_0#6l#6uoj!wdgf9%ruua@_+8qe'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'shopapp.apps.ShopappConfig'

    # 'django_otp',
    # 'django_otp.plugins.otp_totp',
    # 'django_otp.plugins.otp_static',
    # 'django.contrib.sites',
    # 'actstream',  # <-- добавьте сюда
    # 'sslserver',
]
SITE_ID = 1
# TWO_FACTOR_EMAIL_GATEWAY = 'two_factor.gateways.email.EmailDevice'
# TWO_FACTOR_PATCH_ADMIN = True
# LOGIN_URL = 'two_factor:login'
# LOGIN_REDIRECT_URL = '/'
ASGI_APPLICATION = 'sss.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # после AuthenticationMiddleware!
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'sss.urls'
# TWO_FACTOR_PATCH_ADMIN = True  # Важно! Включает 2FA для админки
# LOGIN_URL = 'two_factor:login'  # Перенаправляет на страницу 2FA
# LOGIN_REDIRECT_URL = '/admin/'
# ADMIN_SITE = 'shopapp.admin_site.admin_site'
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'
import os
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')
# Настройки для принудительного выхода
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 60
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sss.wsgi.application'
# LOGIN_URL = 'two_factor:login'
# LOGIN_REDIRECT_URL = 'two_factor:profile'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# URL для доступа к статическим файлам
STATIC_URL = '/static/'
DEBUG = True
# Указываем дополнительные директории для поиска статических файлов (например, в приложении shoapp)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shopapp', 'static'),
]

# Папка, куда будут собраны все статические файлы после выполнения collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'shopapp')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'  # Для Яндекс.Почты
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'yulia.sh3vchenko@yandex.ru'  # Полный email
EMAIL_HOST_PASSWORD = 'zcmkammruaqticxm'  # Пароль приложения (не основной!)
DEFAULT_FROM_EMAIL = 'yulia.sh3vchenko@yandex.ru'
TIME_ZONE = 'Europe/Moscow'  # Для московского времени
USE_TZ = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CSRF_TRUSTED_ORIGINS = [
    'https://mycustomsubdomain.loca.lt',  # Добавьте другие URL, если используете их
]

CELERY_BROKER_URL = 'amqp://guest:guest@localhost//'
CELERY_RESULT_BACKEND = 'rpc://'  # Если вам нужно хранить результаты