# Generated by Django 4.2.18 on 2025-05-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер склона')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='camera_videos/', verbose_name='Видео камеры')),
                ('condition', models.CharField(choices=[('открытая трасса', 'Открытая трасса'), ('Закрытая трасса', 'Закрытая трасса')], max_length=50, verbose_name='Состояние склона')),
            ],
            options={
                'verbose_name': 'Информацию о камере/склоне',
                'verbose_name_plural': 'Информация о камере/склоне',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Информацию о сотрудниках',
                'verbose_name_plural': 'Информация о сотрудниках',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Роль сотрудника',
                'verbose_name_plural': 'Роли сотрудников',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Лог входа сотрудника',
                'verbose_name_plural': 'Логи входов сотрудников',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.role'),
        ),
    ]
